name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Chores'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🎨 Style'
    labels:
      - 'style'
  - title: '♻️ Refactor'
    labels:
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '🔧 Configuration'
    labels:
      - 'config'
      - 'configuration'
template: |
  ## 🎉 Release $RESOLVED_VERSION

  $CHANGES

  ## 📋 Summary

  **Release Date:** $RELEASE_DATE
  **Previous Release:** $PREVIOUS_TAG

  ## 🔗 Links

  - [Full Changelog](https://github.com/SSilvestreS/NexusPM/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
  - [Download](https://github.com/SSilvestreS/NexusPM/releases/tag/$RESOLVED_VERSION)

  ## 🚀 Installation

  ```bash
  # Clone the repository
  git clone https://github.com/SSilvestreS/NexusPM.git
  cd NexusPM

  # Checkout the release
  git checkout $RESOLVED_VERSION

  # Follow installation instructions in README.md
  ```

  ---

  **Obrigado por usar o NexusPM! 🚀**
