name: "Pull Request Auto Delete Branch"

on:
  pull_request:
    types: [closed]

jobs:
  auto-delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const { data: pull } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          
          // Only delete feature branches, not main branches
          const branchName = pull.head.ref;
          const protectedBranches = ['master', 'main', 'develop', 'staging'];
          
          if (!protectedBranches.includes(branchName)) {
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`,
              });
              
              console.log(`Branch ${branchName} deleted successfully`);
            } catch (error) {
              console.log(`Failed to delete branch ${branchName}:`, error.message);
            }
          } else {
            console.log(`Branch ${branchName} is protected and will not be deleted`);
          }
