name: "Pull Request Auto Merge"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.auto_merge
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const { data: pull } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          
          // Check if all checks are passing
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: pull.head.sha,
          });
          
          const allChecksPassing = checks.check_runs.every(check => 
            check.conclusion === 'success' || check.conclusion === 'skipped'
          );
          
          if (allChecksPassing && pull.mergeable) {
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash',
                commit_title: `${pull.title} (#${pull.number})`,
                commit_message: `Closes #${pull.number}`,
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '🚀 **Auto-merged**: All checks passed and PR was automatically merged. Thank you for your contribution!',
              });
            } catch (error) {
              console.log('Auto-merge failed:', error.message);
            }
          }
