name: Release Drafter

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - develop

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          publish: false
          prerelease: ${{ github.ref_name == 'develop' }}
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
